# spring.data.mongodb.uri=mongodb+srv://<username>:<pwd>@<cluster>.mongodb.net/mygrocerylist
spring:
  data.mongodb.uri:mongodb+srv://jitender:L@dyluck1@cluster0.wcrbi.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
  data.mongodb.database:myCustomerList
  kafka:
    consumer:
      group-id=myGroup:
logging:
  level:
    org.springframework: INFO
    com.toyota: DEBUG
pets:
  url:"http://petstore-demo-endpoint.execute-api.com/petstore/pets"
